### ISSUE TITLE
Incorrect string is a difficult error to read

### ISSUE THREAD

**Issue by aturkewi** [learn-co-curriculum/js-basics-online-shopping-lab#15]
I missed a comma in my `viewCart()` function and I got this error:

```
1) shopping #viewCart should print each item in the cart and t
heir cost:                                                      
     AssertionError: expected { Spy, 4 calls } to have been call
ed with [ Array(1) ]                                            
      at Context.it (test/shopping-test.js:58:51)
```

This error was pretty brutal given the simplicity of the problem. Is there any way we can get a cleaner read out like `expected: "Some string", actual: "Some, string"`?

Ref commit for code to reproduce error: 407ce6cabd023c3d2e02c636395963416425dbc8

@pletcher

**Comment by pletcher** [comment]
Thanks for opening this issue!

Keep in mind that this space is for specific issues related to the content of this lesson.

If you're reporting on the content of this lesson, it'd be super helpful if you could include a stack trace of any errors that you're seeing.

If you'd like to report a bug about the Learn IDE, the Ask a Question form, opening a file, or the lights not working on Learn, please report a bug directly on https://learn.co. (You can find the bug report form by clicking on your avatar in the upper right, and then selecting "Report A Bug".)

Please be sure to include steps to reproduce (be as detailed as possible) and any relevant information about your environment. (Are you using the Learn IDE? Coding on a refurbished toaster?) We'll be sure to figure out what's going on — and to jump in and help — just as soon as we can. Thanks!
