### ISSUE TITLE
#addToCart test not working at line 42

### ISSUE THREAD

**Issue by rpalermodrums** [learn-co-curriculum/js-basics-online-shopping-lab#19]
The test only worked once the second argument was removed. Before that I was getting an assertion error

expect(console.log).
        to.
        have.
        been.
        called.
        with(
          "pizza has been added to your cart.",
          "Should have called `console.log()` with 'pizza has been added to your cart.'"); <--removed

AssertionError: expected { Spy, 1 call } to have been called with [ Array(2) ]

**Comment by pletcher** [comment]
Thanks for being a part of the Learn community!

Keep in mind that this space is for specific issues related to the content of this lesson.

If you're reporting on the content of this lesson, it'd be super helpful if you could include a stack trace of any errors that you're seeing.

If you'd like to report a bug about the Learn IDE, the Ask a Question form, opening a file, or the lights not working on Learn, please report a bug directly on https://learn.co. (You can find the bug report form by clicking on your avatar in the upper right, and then selecting "Report A Bug".)

We want to respond as quickly as possible and be as helpful as possible, so please be sure to include steps to reproduce the issue (as best you can remember) and any pertinent details about your environment. (Are you using the Learn IDE? Coding from the ISS?) We'll figure out what's up and get back to you ASAP.

**Comment by rpalermodrums** [comment]
@pletcher FYI same thing happens with the next two tests as well. had to take out the error message (second argument after #with) to make it pass.
