### ISSUE TITLE
Test 10 & 11 

### ISSUE THREAD

**Issue by Lukeghenco** [learn-co-curriculum/js-basics-online-shopping-lab#2]
Test 10 & Test 11 only work if you place a function inside of the placeOrder() function like this:

function placeOrder() {
  // any function that only returns a console log and has no parameters seems to work. I have not tested any functions that use parameters though.
  viewCart();
  if (!cardNumber) {
    console.log("We don't have a credit card on file for you to place your order");
  } else {
    orderNumber++;
    console.log("Your total cost is: $" + total + " and will be charged to the credit card on file (" + cardNumber + "). Your order number is " + (orderNumber - 1));
    total = 0;
    cart = [];
  }
}

it does not make any sense why the test only passes if I call the viewCart() function or another function inside of the placeOrder() function. 

you can check my entire .js file at https://github.com/Lukeghenco/js-basics-online-shopping-lab-v-000/blob/master/shopping.js.

**Comment by Lukeghenco** [comment]
Please let me know if this gets fixed, or if there is really something wrong with this code.

**Comment by jakebrady5** [comment]
Submitted Pull Request with fix for this issue.

**Comment by AnnJohn** [comment]
merged PR. thanks.
