### ISSUE TITLE
Code works in console but doesn't pass tests

### ISSUE THREAD

**Issue by grahk93** [learn-co-curriculum/js-basics-online-shopping-lab#20]
`
function addToCart(item) {
    var price = Math.floor((Math.random()*100));
    new_item = {[item]: price};
    cart.push(new_item);
    console.log(`${item} has been added to your cart.`);
    return cart //getCart()
}

function viewCart() {
  var array = [];
  if(cart.length === 0) {
    console.log("Your shopping cart is empty.");
  } else {
    for(var idx in cart) {
      //{chicken: 20} = cart[idx]
      var item = Object.keys(cart[idx])[0]; //chicken
      var price = cart[idx][item]; //20
      array.push(`${item} at $${price}`)
    }
    console.log(`In your cart, you have ${array.join(", ")}.`);
  }
}
`

**Comment by pletcher** [comment]
Thanks for opening this issue!

Keep in mind that this space is for specific issues related to the content of this lesson.

If you're reporting on the content of this lesson, it'd be super helpful if you could include a stack trace of any errors that you're seeing.

If you'd like to report a bug about the Learn IDE, the Ask a Question form, opening a file, or the lights not working on Learn, please report a bug directly on https://learn.co. (You can find the bug report form by clicking on your avatar in the upper right, and then selecting "Report A Bug".)

Please be sure to include steps to reproduce (be as detailed as possible) and any relevant information about your environment. (Are you using the Learn IDE? Coding on a refurbished toaster?) We'll be sure to figure out what's going on — and to jump in and help — just as soon as we can. Thanks!
