### ISSUE TITLE
Hash

### ISSUE THREAD

**Issue by robhitt** [learn-co-curriculum/js-basics-online-shopping-lab#30]
I could be wrong, however I noticed the top of the lesson at the OBJECTIVES it says "Create and manipulate **hashes**"

Since it's a Javascript lesson should we call this an object instead of a hash or is hash still used in Javascript?

**Comment by aturkewi** [comment]
@cjbrock thoughts? It feels like we could change this over to Object and just add a note saying that JS objects can sometimes look like a ruby hash?

**Comment by aturkewi** [comment]
Don't worry about this @cjbrock sorry for bothering.
I just made the change and merged it in with PR #35
