### ISSUE TITLE
learn.co message window is not displaying properly

### ISSUE THREAD

**Issue by lennhy** [learn-co-curriculum/js-basics-online-shopping-lab#31]
If I open a question, I have to close and reopen the message window every time to read your new message from the instructor.

**Comment by aturkewi** [comment]
Hey @lennhy thanks for bringing this up. I think this one is solved now though, so I'm going to close this. If you are still experiencing a problem with this, please let us know through Ask A Question. Issues raised here are really for issues that are specific to this lab.

Thanks!
