### ISSUE TITLE
If the lesson is about iterating over an object, then why does the test involve iterating over an array?

### ISSUE THREAD

**Issue by catherineluse** [learn-co-curriculum/js-basics-online-shopping-lab#32]
It just seems pretty weird to me that instead of having one object to store all the key-value pairs, the instructions say to add a new object to the array each time we add a key value pair. 

`[{key: value} {key: value}]`

Which means to check if a key is in our array, we have to use a for loop AND iterate through an object, except when we "iterate" we are only iterating once per object. I don't see the point. Why don't we just have one object with all key-value pairs?

`{key: value, key: value}

**Comment by gj** [comment]
Hi @catherineluse !

As you correctly point out, there's no need to iterate through objects at all in this lab, so it didn't make a whole lot of sense to introduce object iteration here.

To your question about replacing our `cart` array of objects with a nested `cart` object, I think an array is a better data structure for representing the idea of a shopping cart. The items are placed in the cart, but it's hard for me to see them as representing _properties_ of the cart.

Thanks so much for pointing this out, and I hope e678be6 clears up the confusion for future students.
