### ISSUE TITLE
`js-intro-000` copy out of sync

### ISSUE THREAD

**Issue by bhollan** [learn-co-curriculum/js-basics-online-shopping-lab#44]
It looks like someone committed directly to the batch's copy of the lab:
https://github.com/learn-co-students/js-basics-online-shopping-lab-v-000/commit/b4fc238e48951515ad19364900c976a02676e4c2

...changed the content of the lab to be completely unrelated to the lesson's content.

CC: @aturkewi

**Comment by aturkewi** [comment]
All set. Thanks for raising this.
