### ISSUE TITLE
open button links old/outdated project with no package.json/ root.js etc...

### ISSUE THREAD

**Issue by survivingknowledge** [learn-co-curriculum/js-basics-online-shopping-lab#48]
open button links to 
maybe community version didn't get updated?
https://github.com/learn-co-students/js-basics-online-shopping-lab-cb-000
which doesn't have package.json
and root.js/mocha.opts files
filesto get it to work are in aturkewi-patch-1 branch

needs to be changed to new repo
https://github.com/learn-co-students/js-basics-online-shopping-lab-v-000

**Comment by JessRudder** [comment]
Hi @survivingknowledge - the open button link is generated on a per user basis.  It could be generating that link if you'd previously done this lesson as part of Community-Powered Bootcamp.  If that's not the case and you're still seeing this issue, please let us know.
