### ISSUE TITLE
There is no index.js

### ISSUE THREAD

**Issue by TaylorWatson** [learn-co-curriculum/js-basics-online-shopping-lab#51]
Even if I add an index.js the learn terminal isn't setup for this. It's completely broken.

**Comment by gj** [comment]
Hey @TaylorWatson !

This sounds like a cloning issue — are you using the Learn IDE?

Best way to get support for an issue like this is by using the [Ask a Question](http://help.learn.co/ask-a-question/how-to-ask-a-good-question) feature on [Learn.co](https://learn.co/).
