### ISSUE TITLE
I've managed to get everything running in browser, but can't fix 7 issues on this one IDE side.

### ISSUE THREAD

**Issue by kazenorite** [learn-co-curriculum/js-basics-online-shopping-lab#52]
![yet 7 things with problems](https://cloud.githubusercontent.com/assets/5590833/25100894/ff40c6ea-237f-11e7-802d-44d4a6c62556.png)
![the 7 things with problems](https://cloud.githubusercontent.com/assets/5590833/25100934/2330c618-2380-11e7-9114-e42cf7d16c47.png)
I can't get any of these 7 problems to resolve.  I have tried numerous times, with several approaches, but can't get them to pass.  The code I've written is written below.
![code in question](https://cloud.githubusercontent.com/assets/5590833/25101399/25cd748c-2382-11e7-9f69-909312be0ca5.png)
![code in question2](https://cloud.githubusercontent.com/assets/5590833/25101407/2b2ca006-2382-11e7-9966-2702545f1a5c.png)
![code in question3](https://cloud.githubusercontent.com/assets/5590833/25101411/31357220-2382-11e7-8ce7-9a2c4a514d2b.png)
Thank you for your time.

**Comment by JessRudder** [comment]
Hi @kazenorite - thanks for reaching out.  For help on writing code for a specific lab, please use the "Ask a Question" feature on the right side of Learn.  If you're in a supported track, you will receive help from Learn Experts.  If not, other people in the class should be able to help you resolve your issues.
