### ISSUE TITLE
Online Shopping Lab is broken. Wrong lesson inside

### ISSUE THREAD

**Issue by nechitai** [learn-co-curriculum/js-basics-online-shopping-lab#54]
When I press Open on the[Online Shopping Lab page](https://learn.co/tracks/full-stack-community-bootcamp/javascript-foundations/data-structures/online-shopping-lab), I get here, but this is Time Complexity lesson, and it has no index.js file. So there is no way to solve it, currently.

**Comment by nataliemona** [comment]
This is the correct lesson https://github.com/learn-co-students/js-basics-online-shopping-lab-js-intro-000

**Comment by gj** [comment]
Hi @nechitai !

I'm so sorry about this — simple deployment mistake. Fixed now!
