### ISSUE TITLE
Cannot Open Online Shopping Lab.

### ISSUE THREAD

**Issue by fullstackdev1** [learn-co-curriculum/js-basics-online-shopping-lab#56]
Hi Tech Coach Team,

I am having some technical difficulties simply trying to open the Online Shopping Lab.  

learn open js-basics-online-shopping-lab-v-000
Looking for lesson...
Forking lesson...
Cloning lesson...
There was a problem cloning this lesson.  Retrying...
Cloning lesson...
There was a problem cloning this lesson.  Retrying...
Cloning lesson...
Cloning lesson...
Cannot clone this lesson right now.  Please try again.

Please help.

Thanks.

Pat

**Comment by gj** [comment]
Hi @fullstackdev1,

The [Technical Coaches](http://help.learn.co/instructional-support/receiving-course-support/who-are-the-technical-coaches) can help you out with this if you use the [Ask a Question](http://help.learn.co/ask-a-question) feature. 🙂
