### ISSUE TITLE
Cannot pass the test for the online shopping lab

### ISSUE THREAD

**Issue by lrr0323** [learn-co-curriculum/js-basics-online-shopping-lab#59]
Hi! I have some issue with the viewCart function. I was able to print the desired outcome with my codes but when I "learn test", it comes back with error like "spy was never called with ['In your cart, you have lemons at $50.']

Here is my codes and the error

![image](https://user-images.githubusercontent.com/29445063/27294453-36a49708-554c-11e7-9c40-fb750d582423.png)

**Comment by gj** [comment]
Hi @lrr0323 !

This is the type of question that you should use [the Ask a Question feature](help.learn.co/ask-a-question/how-to-ask-a-good-question) for. Raising a GitHub issue is for when you encounter an error with the actual curriculum — not just a difficult test. 🙂 

In the code snippet you pasted, the test is running correctly. To see the error in your code, I'd recommend you open up `index.html` in your browser ([here](http://help.learn.co/the-learn-ide/common-ide-questions/viewing-html-pages-in-the-learn-ide) are instructions if you're using the Learn IDE), add a few items to your `cart` with the `addToCart()` function, and then try printing out your `cart` with the `viewCart()` function. Pay close attention to the output of your function versus the output that the test suite is expecting for each individual test (e.g., `'In your cart, you have lemons at $2.' ` in the `Error: spy was never called with [ 'In your cart, you have lemons at $2.' ]` error message).

When you can't figure out what the tests are telling you, debugging by actually trying to use the code for its designed purpose is a great way to troubleshoot errors (and to generally get some feedback about how functional your code is).

Hope that helps!
