### ISSUE TITLE
Problem With Getting A Test To Run

### ISSUE THREAD

**Issue by cubsfan46350** [learn-co-curriculum/js-basics-online-shopping-lab#60]
var cart = [];
var item;
function getCart() {
 return cart;
}

function setCart(c) {
  cart = c;
  return cart;
}

function addToCart(item) {
  var addItem = {[item]: Math.floor(Math.random() * 100)}
  cart.push(addItem);
  console.log(`${item} has been added to your cart.`)
  return cart;
}

function viewCart() {
  if (cart.length <= 0) {
    console.log('Your shopping cart is empty.');
  }
  for (var i = 0; i <= cart.length; i++) {
      console.log(`In your cart, you have ${item} at $` + Math.floor(Math.random() * 100) + `.`);
    }
    return cart;
  }

Error Message Received From Test:1) viewCart() correctly prints a one-item cart:
     Error: spy was never called with [ 'In your cart, you have lemons at $74.' ]
      at assert (node_modules/expect/lib/assert.js:29:9)
      at Expectation.toHaveBeenCalledWith (node_modules/expect/lib/Expectation.js:333:28)
      at Context.<anonymous> (test/index-test.js:92:25)

**Comment by gj** [comment]
Hi @cubsfan46350 !

This is the type of question that you should use [the Ask a Question feature](help.learn.co/ask-a-question/how-to-ask-a-good-question) for. Raising a GitHub issue is for when you encounter an error with the actual curriculum — not just a difficult test. 🙂 

In the code snippet you pasted, the test is running correctly. To see the error in your code, I'd recommend you open up `index.html` in your browser ([here](http://help.learn.co/the-learn-ide/common-ide-questions/viewing-html-pages-in-the-learn-ide) are instructions if you're using the Learn IDE), add a few items to your `cart` with the `addToCart()` function, and then try printing out your `cart` with the `viewCart()` function.

When you can't figure out what the tests are telling you, debugging by actually trying to use the code for its designed purpose is a great way to troubleshoot errors (and to generally get some feedback about how functional your code is).

Hope that helps!
