### ISSUE TITLE
placeOrder directions unclear

### ISSUE THREAD

**Issue by TcFlux** [learn-co-curriculum/js-basics-online-shopping-lab#64]
Not really an issue but instruction #20 just makes it seem like you are supposed to print "Your total cost is $71, which will be charged to the card 83296759." Instead of actually using the total() and using the cardNumber argument.

**Comment by gj** [comment]
Fixed in https://github.com/learn-co-curriculum/js-basics-online-shopping-lab/commit/f936f73363f3b2f9caa14404449dd9b97ce71051. Thanks @TcFlux !
