### ISSUE TITLE
Issue with Test Suite

### ISSUE THREAD

**Issue by Laurenaustin** [learn-co-curriculum/js-basics-online-shopping-lab#65]
The test for placeOrder() without a card number should add an item to the cart before invoking the spy. In order to get the test to pass I needed to add the condition that cart.length !== 0 in addition to the condition of a card number being passed in as an arg, which isn't really what the lesson says it is testing for. (The former condition is irrelevant to whether or not the system has a user's card number on file.) Hope this helps!

**Comment by sgharms** [comment]
@Laurenaustin 

I was able to pass the test without adding this condition. Based on a non-code description, I think you might have a bug in the `total` code which is called from `placeOrder`. Take a second look, get a second opinion and, if you're still stuck, push your solution branch to this repo  and re-open the issue and I'll see if I've missed something.
