### ISSUE TITLE
Oxford Comma confusion

### ISSUE THREAD

**Issue by eckmLJE** [learn-co-curriculum/js-basics-online-shopping-lab#69]
**Lab Objective:**
> Brush up on conditionals and control flow to make some _Oxford comma magic happen_.

**Assume the following shapes according to how many items the cart contains:**
> 3+ items — In your cart, you have bananas at $17, pancake batter at $5, and eggs at $49.

**However**, the actual test will fail the presence of an oxford comma. The test requires there to be no oxford comma for a 3+ shopping cart in the viewCart() function. If this is intentional confusion to trip people up, kudos.

**Comment by DakotaLMartinez** [comment]
@curiositypaths 

Shall we add a comma to the tests here to match the README, or change the README to match the test? Given the objectives, I'm leaning towards adding a comma to the tests.

**Comment by curiositypaths** [comment]
Hi there,

Thank you for bringing this to our attention. We just updated the README, test and sample solution to properly account for the Oxford comma.

As always thank you for contributing.
