### ISSUE TITLE
Typo in 'index-test.js' for addToCart()

### ISSUE THREAD

**Issue by justckim** [learn-co-curriculum/js-basics-online-shopping-lab#71]
Test: it("sets the price (integer between 1 and 100) on the cart object using the key `price`",

I was struggling with why the test was giving an undefined error. It was not until I looked more closely inside the test that I realized it's because the key should be itemPrice, not price. 

I think it would be less confusing if this was changed to "using the key `itemPrice`"

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
