### ISSUE TITLE
Solution does not work

### ISSUE THREAD

**Issue by justinddaniel** [learn-co-curriculum/js-basics-online-shopping-lab#72]
As of May 8th, 2018, using the solution in the solution branch on GitHub results in most tests failing.

**Comment by maxwellbenton** [comment]
Hi there @justinddaniel,

I'm having difficulty reproducing the issue. The solution branch does correctly pass all tests both in the in-browser IDE and in a local environment.

If you can provide further detail about the steps required to reproduce the issue and any additional relevant information about your development environment (local or IDE), I'd be happy to take a second look!

As always, thanks for contributing! 💙
