### ISSUE TITLE
IDE Problem

### ISSUE THREAD

**Issue by kyleverret** [learn-co-curriculum/js-basics-online-shopping-lab#73]
I am having a trouble with the IDE in the Basics Online Shopping Lab
The following error occurs. After running "learn" once the IDE becomes unresponsive.

Opening lesson...
Installing npm dependencies...
yarn install v1.6.0[1/4] Resolving packages...
warning babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
warning mocha > to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
warning mocha > glob > minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
warning mocha > jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
warning Your current version of Yarn is out of date. The latest versi
on is "1.7.0", while you're on "1.6.0".
info To upgrade, run the following command:
$ sudo apt-get update && sudo apt-get install yarn

**Comment by srscalia** [comment]
I am having a similar issue. Any luck with solving?

**Comment by drakeltheryuujin** [comment]
Hi there! This request sounds like an improvement to the Learn platform.
[Raising issues on GitHub][raise] should be reserved for problems with the
curriculum itself (doesn't work, throws a Ruby error, etc.). If Learn
is misbehaving, please direct your bug report to bugs@learn.co.

If, on the other hand, we've misunderstood the purpose of this request, please
re-open this issue, provide any additional information you can, and we will try
to discern a proper path to resolution.

[raise]: http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson
