### ISSUE TITLE
The tests do not match the format given in the instructions

### ISSUE THREAD

**Issue by mikkel250** [learn-co-curriculum/js-basics-online-shopping-lab#79]
The instructions state:
The object should consist of two key-value pairs : { itemName: name of the item, itemPrice: price of the item, }

When structured this way (above), the test fails: 
 1) addToCart() properly structures objects in the { itemName: itemPrice } format:

      Error: Expected 'item' to equal 'daikon'
      + expected - actual

      -item
      +daikon

      at assert (node_modules/expect/lib/assert.js:29:9)
      at Expectation.toEqual (node_modules/expect/lib/Expectation.js:81:30)
      at Context.<anonymous> (test/index-test.js:38:22)

The test is expecting the format to be item: price
NOT 
itemName: item, itemValue: price

So either the test or the instructions should be changed

**Comment by samreeve95** [comment]
Has this been fixed?
Because, at present, my cart array consists of objects possessing two key:value pairs.
And I do not receive this error.
Is it possible that the fault arises due to "item" being interpreted as a string literal instead of a variable?

**Comment by lizbur10** [comment]
Hi there! Thank you for catching this issue and for submitting feedback. This error has now been corrected in the lab's test files. Apologies for the inconvenience you experienced as a result of this error.

Thanks for contributing to the Flatiron School curriculum. 💙
