### ISSUE TITLE
My test is passing but its coming back as failing all tests when I run learn. 

### ISSUE THREAD

**Issue by Louiefigz** [learn-co-curriculum/js-basics-online-shopping-lab#8]
I'm able to see that I'm passing all tests when I'm running learn -b. However, when I run learn, Im failing all tests and its reading as failed local tests when I push my code to github.  Im wondering if it is my code that's broken or not.  Thanks

**Comment by AnnJohn** [comment]
hi @Louiefigz since this is a technical problem or one that's specific to your code, can you use the Ask a Question feature or file a bug report? Thanks!
