### ISSUE TITLE
Test explanations are incorrect to what the test is testing.

### ISSUE THREAD

**Issue by ringlemans** [learn-co-curriculum/js-basics-online-shopping-lab#89]
```js
  it("sets the price (integer between 1 and 100) on the cart object using the key `price`", function() {
```
This is asking for the object key to be set as price. As we see on the next line in the test,
```js
let itemPrice = getCart()[0].itemPrice;
```
You are looking for the key itemPrice. This is confusing and can be easily remedied. I will open a pr to fix.

**Comment by lizbur10** [comment]
Hi there! Thank you for catching this issue and for submitting feedback. This error has now been corrected in the lab's tests. Apologies for the inconvenience you experienced as a result of this error.

Thanks for contributing to the Flatiron School curriculum.
