### ISSUE TITLE
'Price' key?

### ISSUE THREAD

**Issue by skabe89** [learn-co-curriculum/js-basics-online-shopping-lab#91]
I've finished everything in this lab but  the one failing test; "_**1) sets the price (integer between 1 and 100) on the cart object using the key `price`**_" in the addToCart function. Everything else in my code works. I'm having trouble figuring out what it wants so that I can submit my work. If anyone has any insight on what I need to do and would like to share that would be great.

While inefficient, this is what my addToCart function looks like right now,

function addToCart(item) {
 var place = cart
 var price = parseInt(Math.floor(Math.random()*100))
 place.push({itemName: `${item}`, itemPrice: `${price}`})
 if (place.length == cart.length + 1) {return `${item} has been added to your cart`}
  else {return `${item} has been added to your cart.`}
  return place
}

**Comment by lizbur10** [comment]
Hi there! Thank you for catching this issue and for submitting feedback. This was an error in the lab's test files, and has now been corrected. Apologies for the inconvenience you experienced as a result of this error.

Thanks for contributing to the Flatiron School curriculum.
